language: node_js

node_js:
  - stable

before_script:
  - git config --global user.email "fo@bar.com"
  - git config --global user.name "Foo Bar"
  - npm install --save-dev mocha
  - npm install -g mocha

script:
  - npm test

notifications:
  email:
    recipients:
      - tejact2007@gmail.com
    on_success: always
    on_failure: always


